/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteVoicebankRouteImport } from './routes/_site/voicebank'
import { Route as SiteWorksRouteImport } from './routes/_site/works'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteVoicebankRoute = SiteVoicebankRouteImport.update({
  id: '/voicebank',
  path: '/voicebank',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWorksRoute = SiteWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/voicebank': typeof SiteVoicebankRoute
  '/works': typeof SiteWorksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/voicebank': typeof SiteVoicebankRoute
  '/works': typeof SiteWorksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/voicebank': typeof SiteVoicebankRoute
  '/_site/works': typeof SiteWorksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/voicebank' | '/works'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/voicebank' | '/works'
  id:
    | '__root__'
    | '/'
    | '/_site'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/voicebank'
    | '/_site/works'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/voicebank': {
      id: '/_site/voicebank'
      path: '/voicebank'
      fullPath: '/voicebank'
      preLoaderRoute: typeof SiteVoicebankRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/works': {
      id: '/_site/works'
      path: '/works'
      fullPath: '/works'
      preLoaderRoute: typeof SiteWorksRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteVoicebankRoute: typeof SiteVoicebankRoute
  SiteWorksRoute: typeof SiteWorksRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteVoicebankRoute: SiteVoicebankRoute,
  SiteWorksRoute: SiteWorksRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
